[phases.setup]
nixPkgs = ['jdk17', 'gradle']

[phases.build]
cmds = ['chmod +x./gradlew',
    './gradlew clean buildFatJar']

[start]
cmd = 'java -jar build/libs/ktor-sample.jar'

[container]
memory = 512